version: '2'
services:
  mongodb:
    image: scottford/np-mongodb
    command: --strategy at-once
    environment:
      HAB_MONGODB: "[mongod.net]\nbind_ip = '0.0.0.0'\n[mongod.security]\ncluster_auth_mode = ''"
  national-parks:
    image: scottford/national-parks
    ports:
      - 8081:8080
      - 9631:9631
    links:
      - mongodb
    depends_on:
      - mongodb
    command: --strategy at-once --channel unstable --peer mongodb --bind database:np-mongodb.default
